baseURL="http://hechen0.com"
theme = "coder"
googleAnalytics = "UA-57183016-8"
pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
    author = "何晨"
    description = "技术成长之道"
    keywords = "博客,developer"

[[params.social]]
    name = "Blog"
    weight = 1
    url = "/posts/"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/hechen0/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/hechen0_/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "Home"
    weight = 2
    url = "/"
