baseURL="http://hechen0.com"
theme = "coder"
googleAnalytics = "UA-57183016-8"

[params]
    author = "何晨"
    description = "一届码农"
    keywords = "博客,开发者"

[[params.social]]
    name = "博客"
    weight = 1
    url = "/posts/"
[[params.social]]
    name = "Github"
    weight = 2
    url = "https://github.com/hechen0/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/hechen0_/"

[[menu.main]]
    name = "博客"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "主页"
    weight = 2
    url = "/"